
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./Components/Header/Navbar";
import Background from "./Components/Background/Background";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <Background/>
        {children}
      </body>
    </html>
  );
}